# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

# Scheduled function 
[functions."dailyVacationsReport"]
  schedule = "0 5 * * 1-5"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
